### PR TITLE
Add valid_time to TIME_NAMES and fix issue with pretty printing

### LINKED ISSUE #204: Pretty print when dictionaries are empty throw an error
When the dictionaries of the `OutputVar` are empty, then printing will throw an error when trying to compute the amount of padding to add.

There should be tests that test for the empty OutputVar and when the dictionaries are empty.

### LINKED ISSUE #205: Add compatibility for reading NetCDF files from ERA5
The time dimension is called `valid_time` in the NetCDF file. The name should also be in `ClimaAnalysis.Var.TIME_NAMES`.

### PR DESCRIPTION
**Pull request by ph-kev**
closes #204, closes #205 - The issue with pretty printing is when the `OutputVar` has empty dictionaries in which the padding cannot be computed. The other potential issue is when the value of `dim_attributes` is something that is not a dictionary.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
I don't think there should be a case where `dim_attributes` is not a dict. It's type is `OrderedDict{String, C}` in the type definition

**Comment by ph-kev** [comment]
> I don't think there should be a case where `dim_attributes` is not a dict. It's type is `OrderedDict{String, C}` in the type definition

I realized that I poorly wrote that sentence. I mean that `C` can be something that is not a dictionary.

**Comment by ph-kev** [comment]
> > > I don't think there should be a case where `dim_attributes` is not a dict. It's type is `OrderedDict{String, C}` in the type definition
> > 
> > 
> > I realized that I poorly wrote that sentence. I mean that `C` can be something that is not a dictionary.
> 
> Are we encountering these cases in the wild? Which other `C`s do we have to deal with?

I don't think this ever appear in the wild, but we don't restrict what `C` could be in the struct for an `OutputVar`. I agree that there shouldn't be a case where `dim_attributes` is not a `Dict`. Should I add the constraint for what `C` is in the `OutputVar`?

File: src/Var.jl [hunk 1]
```diff
@@ -1897,14 +1901,19 @@ function Base.show(io::IO, var::OutputVar)
...
             end
-        end
-        if length(array) == 1
+        elseif length(array) == 1
             print(io, "element")
             print(io, " (")
             printstyled(io, "$(array[begin])", color = :light_cyan)
             print(io, ")")
+        else
+            length(array) == 0
```
Comment (Sbozzolo) [inline src/Var.jl:1910]:
```suggestion
        elseif length(array) == 0
```

**Review by Sbozzolo — APPROVED** [review]
